import { createClient } from '@supabase/supabase-js';
const U="https://qkjpxrzbzxxjevxrgfgd.supabase.co", K="sb_publishable__XyAhr1EGXwpBGwJ32YyKQ_TevyWbha";
const parent = createClient(U,K,{auth:{persistSession:false}});
const kid = createClient(U,K,{auth:{persistSession:false}});
const ok=(l,r)=>{ if(r.error) throw new Error(l+': '+r.error.message); console.log('✓',l); return r.data; };
const email=`e2e-${Date.now()}@chorelock.dev`;
ok('parent signup', await parent.auth.signUp({email,password:'testpass123'}));
const fid = ok('create_family', await parent.rpc('create_family',{family_name:'E2E fam',parent_name:'Sage'}));
const k = ok('add kid', await parent.from('kids').insert({family_id:fid,name:'Dawson',age:9}).select().single());
const c = ok('add chore', await parent.from('chores').insert({family_id:fid,name:'Feed the dog',emoji:'🐶'}).select().single());
ok('assign', await parent.from('chore_assignments').insert({chore_id:c.id,kid_id:k.id}));
ok('ensure_today (parent)', await parent.rpc('ensure_today',{p_kid:k.id}));
ok('kid anon signin', await kid.auth.signInAnonymously());
ok('join_as_kid', await kid.rpc('join_as_kid',{code:k.join_code}));
const mine = ok('kid reads instances', await kid.from('chore_instances').select('*'));
console.log('  kid sees', mine.length, 'instance(s), status', mine[0]?.status);
const path=`${fid}/${k.id}/${mine[0].date}/${c.id}-1.jpg`;
ok('kid uploads photo', await kid.storage.from('proofs').upload(path,new Blob([new Uint8Array([255,216,255,217])],{type:'image/jpeg'})));
ok('kid submits', await kid.from('chore_instances').update({status:'submitted',photo_path:path,submitted_at:new Date().toISOString()}).eq('id',mine[0].id));
const bad = await kid.from('chore_instances').update({status:'approved'}).eq('id',mine[0].id).select();
console.log(bad.data?.length===0 || bad.error ? '✓ kid CANNOT self-approve' : '✗ kid self-approved!');
const other = await kid.from('kids').select('*'); console.log('  kid sees', other.data.length, 'kid row(s) (expect 1)');
ok('parent signed url', await parent.storage.from('proofs').createSignedUrl(path,60));
ok('parent approves', await parent.from('chore_instances').update({status:'approved'}).eq('id',mine[0].id));
const st = ok('lock state', await kid.from('kid_lock_state').select('state').single()); console.log('  state =', st.state);
ok('parent override lock', await parent.rpc('set_override',{p_kid:k.id,mode:'lock'}));
console.log('  after override =', (await kid.from('kid_lock_state').select('state').single()).data.state);
ok('streak', await kid.rpc('kid_streak',{p_kid:k.id})).toString && console.log('  streak =', (await kid.rpc('kid_streak',{p_kid:k.id})).data);
ok('cleanup', await parent.from('families').delete().eq('id',fid));
